name: Spliced Analysis
on:
  pull_request: []
  workflow_dispatch: 
    inputs:
      package_pattern:
        description: 'Name of experiment.yaml pattern (in buildsi/spliced-experiment splices) to test.'
        required: true
      skip_smeagle:
        description: 'Skip Smeagle if it caused the runs to fail (e.g., memory)'
        required: true
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        # container, compiler inside to use, and name+version to save
        container: [['ghcr.io/buildsi/ubuntu:ubuntu-18.04', 'gcc' , 'gcc-7.5.0'],
                    ['ghcr.io/buildsi/ubuntu:ubuntu-18.04', 'g++' , 'gpp-7.5.0'],
                    ['ghcr.io/buildsi/ubuntu:ubuntu-20.04', 'gcc' , 'gcc-9.4.0'],
                    ['ghcr.io/buildsi/ubuntu:ubuntu-20.04', 'g++' , 'gpp-9.4.0'],
                    ['ghcr.io/buildsi/ubuntu:ubuntu-22.04', 'gcc' , 'gcc-11.2.0'],
                    ['ghcr.io/buildsi/ubuntu:ubuntu-22.04', 'g++' , 'gpp-11.2.0'],                                      
                    ['ghcr.io/buildsi/intel:intel-2022.2-devel-ubuntu20.04', 'dpcpp', 'dpcpp-2022.2'],
                    ['ghcr.io/buildsi/intel:intel-2021.4-devel-ubuntu18.04', 'dpcpp', 'dpcpp-2021.4'],
                    ['ghcr.io/buildsi/llvm:llvm-6', 'clang', 'clang-6'],
                    ['ghcr.io/buildsi/llvm:llvm-7', 'clang', 'clang-7'],
                    ['ghcr.io/buildsi/llvm:llvm-8', 'clang', 'clang-8'],
                    ['ghcr.io/buildsi/llvm:llvm-9', 'clang', 'clang-8'],
                    ['ghcr.io/buildsi/llvm:llvm-10', 'clang', 'clang-10'],
                    ['ghcr.io/buildsi/llvm:llvm-11', 'clang', 'clang-11'],
                    ['ghcr.io/buildsi/llvm:llvm-12', 'clang', 'clang-12'],
                    ['ghcr.io/buildsi/llvm:llvm-13', 'clang', 'clang-13'],
                    ['ghcr.io/buildsi/llvm:llvm-14', 'clang', 'clang-14']]
        
    container:
      image: ${{ matrix.container[0] }}
      options: "--platform=linux/amd64"

    name: ${{ matrix.container[2] }}
    steps:
      - name: Show Job Config
        run: |
           echo ${{ matrix.container[0] }}
           echo ${{ matrix.container[1] }}
           echo ${{ matrix.container[2] }}

      - name: Make Space For Build
        run: |        
          ls /usr/share
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: buildsi/smeagle-examples
          ref: breakages/enum

        # Install deps cle, abi-laboratory, spliced, etc. into container
      - name: Update container base with predictors and spliced
        uses: buildsi/smeagle-examples/actions/install@breakages/enum

      - name: Run Build
        env:
          SPLICED_SMEAGLE_CACHE_DIR: /cache
          SPLICED_ABILAB_CACHE_DIR: /cache
          CXX: ${{ matrix.container[1] }}
          compiler: ${{ matrix.container[2] }}
          skip_smeagle: ${{ github.event.inputs.skip_smeagle }}
        run: |
           root=$PWD           
           export PATH=/usr/local/bin:${PWD}:/${PWD}/actions/scripts:/usr/bin:$PATH
           mkdir -p /tmp/diff-results /cache
           ls
           rm -rf _development
           CXX=${CXX} /bin/bash build.sh
           for category in $(ls -d */); do
               printf "Inspecting category ${category}\n"
               cd ${root}/${category}
               ls
               original=example
               if ! test -f ${original}; then
                   original=lib.so
               fi
               original=$(realpath ${original})
               printf "Found libA ${original}\n"
               if test -d ./breaks; then
                   for dir in $(ls ./breaks); do
                       printf "Looking at break ${dir}\n"
                       break_dir=${root}/${category}/breaks/${dir}
                       cd ${break_dir}
                       ls
                       splice="example"
                       if ! test -f ${splice}; then
                           splice=lib.so
                       fi
                       splice=$(realpath ${splice})
                       printf "Found libB ${splice}\n"
                       outdir="/tmp/diff-results/${category}${dir}/${compiler}"
                       mkdir -p ${outdir}
                       experiment=${original}-${splice}-${compiler}
                       outfile="${outdir}/experiment.json"
                       echo ${compiler} >> ${outdir}/compiler.txt
                       cmd="spliced diff --package ${original} --splice ${splice} --experiment ${experiment} --runner manual --outfile ${outfile} --skip spack-test" 
                       if [ "${skip_smeagle}" == "true" ]; then
                           cmd="${cmd} --skip-smeagle"
                       fi
                       printf "${cmd}\n"
                       ${cmd}
                       cat ${outfile}
                   done
               fi
           done
      - name: Save result artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.container[2] }}
          path: /tmp/diff-results

      - name: Save Smeagle Cache
        uses: actions/upload-artifact@v3
        with:
          name: cache-smeagle-${{ matrix.container[2] }}
          path: /cache/smeagle-spack
