name: ABI Fedora Diffs
on:
  pull_request: []
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        # container, compiler inside to use, and name+version to save
        container: [['ghcr.io/buildsi/fedora:fedora-34', "34"],
                    ['ghcr.io/buildsi/fedora:fedora-35', "35"],
                    ['ghcr.io/buildsi/fedora:fedora-36', "36"],
                    ['ghcr.io/buildsi/fedora:fedora-37', "37"]]

    container:
      image: ${{ matrix.container[0] }}
      options: "--platform=linux/amd64"

    name: ${{ matrix.container[0] }} Fedora ${{ matrix.container[1] }}
    steps:
      - name: Show Job Config
        run: |
           echo ${{ matrix.container[0] }}
           echo ${{ matrix.container[1] }}

      - name: Make Space For Build
        run: |        
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Fedora Libs
        run: /bin/bash fedora_installs.sh

      - name: Move Fedora Libs
        run: |
          mkdir -p ./libs
          cp -R /lib64/* ./libs/

      - name: View Fedora Libs
        run: tree ./libs

      - name: Upload Libs
        uses: actions/upload-artifact@v3
        with:
          name: fedora-libs-${{ matrix.container[1] }}
          path: ./libs

  abi:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        lib: ["libadwaitaqtpriv.so",
              "libaspell.so",
              "libboost_log.so",
              "libclucene-core.so",
              "libdap.so",
              "libdcerpc-samr.so",
              "libdjvulibre.so",
              "dovecot/libdovecot-storage.so",
              "libexiv2.so",
              "libgdal.so",
              "libgeos.so",
              "libglibmm-2.4.so",
              "mozilla/plugins/gmp-gmpopenh264/system-installed/libgmpopenh264.so",
              "libhdf5_cpp.so",
              "libicui18n.so",
              "libicuuc.so",
              "dyninst/libinstructionAPI.so",
              "libjavascriptcoregtk-4.0.so",
              "libjxl.so",
              "libkmldom.so",
              "libmusicbrainz5.so",
              "libOpenEXRUtil-3_1.so",
              "libopenh264.so",
              "libOSMesa.so",
              "libproj.so",
              "libQt5WaylandClient.so",
              "libQt5WaylandCompositor.so",
              "libQt5XmlPatterns.so",
              "libSDL2_image-2.0.so",
              "libstdc++.so",
              "libtag.so",
              "libreoffice/program/libuno_cppuhelpergcc3.so",
              "libvtkRenderingCore.so",
              "libwebrtc_audio_processing.so",
              "libicui18n.so",
              "libicuuc.so"]

        # Artifact pairs (named) for comparison)
        artifacts: [["fedora-libs-34", "fedora-libs-35"],
                    ["fedora-libs-34", "fedora-libs-36"],
                    ["fedora-libs-34", "fedora-libs-37"],
                    ["fedora-libs-35", "fedora-libs-36"],
                    ["fedora-libs-35", "fedora-libs-37"],
                    ["fedora-libs-36", "fedora-libs-37"]]

    # Any base container will do, we already have the libs!
    container:
      image: ghcr.io/buildsi/ubuntu:ubuntu-22.04
      options: "--platform=linux/amd64"

    name: ${{ matrix.artifacts[0] }} vs ${{ matrix.artifacts[1] }} ${{ matrix.lib }}
    steps:
    - name: Make More Room
      run: |        
        rm -rf /usr/share/dotnet
        rm -rf /opt/ghc

    - name: Download First Version
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifacts[0] }}
        path: first/

    - name: Download Second Version
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifacts[1] }}
        path: second/

    - name: View Artifacts Structure
      run: |
        ls first/
        ls second/

    - name: Update container base with predictors and spliced
      uses: buildsi/smeagle-examples/actions/install@main

    - name: Checkout
      uses: actions/checkout@v3

    - name: Compare Matching Libs
      run: /bin/bash run_spliced_tests.sh ${{ matrix.lib }}


#      - name: Save result artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ matrix.container[2] }}
#          path: /tmp/diff-results

#      - name: Save Smeagle Cache
#        uses: actions/upload-artifact@v3
#        with:
#          name: cache-smeagle-${{ matrix.container[2] }}
#          path: /tmp/cache
