name: ABI Fedora Diffs
on:
  pull_request: []
  workflow_dispatch: 
    inputs:
      start:
        description: 'Start index for doing analysis'
        required: true
        default: 0
      stop:
        description: 'End index for doing analysis'
        required: true
        default: 5000


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        # container, compiler inside to use, and name+version to save
        container: [['ghcr.io/buildsi/fedora:fedora-34', "34"],
                    ['ghcr.io/buildsi/fedora:fedora-35', "35"],
                    ['ghcr.io/buildsi/fedora:fedora-36', "36"],
                    ['ghcr.io/buildsi/fedora:fedora-37', "37"]]

    container:
      image: ${{ matrix.container[0] }}
      options: "--platform=linux/amd64"

    name: ${{ matrix.container[0] }} Fedora ${{ matrix.container[1] }}
    steps:
      - name: Show Job Config
        run: |
           echo ${{ matrix.container[0] }}
           echo ${{ matrix.container[1] }}

      - name: Make Space For Build
        run: |        
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Checkout
        uses: actions/checkout@v3

      - name: Installation setup
        run: |
          mkdir -p ./libs/usr/lib/debug
          dnf install -y dnf-plugins-core

      - name: Install Fedora Libs
        run: |
          mkdir -p ./libs
          /bin/bash fedora_installs.sh

      - name: Install complete debuginfo files
        run: |
          packages=$(find /usr/lib64 /usr/lib -type f -name "*.so*" | xargs rpm -qf | sort -u)
          for p in ${packages[*]}; do dnf debuginfo-install -y $p; done

      - name: Copy debuginfo files
        run: |
          ln -fs /usr/lib/debug/usr -t libs/usr/lib/debug
          ln -fs /usr/lib/debug/.dwz -t libs/usr/lib/debug

      - name: Copy library files
        run: |
          # Copy files from /usr/lib and /usr/lib64 with names containing the
          # string '.so' that are not symlinks and do not live in /usr/lib/debug
          find /usr/lib/ /usr/lib64/ -type f -iname "*.so*" ! -type l -not -path "/usr/lib/debug/*" -exec cp -u --parents {} libs/ \;
          
      - name: Remove unwanted lib files
        run: |
          for s in py pyc sob soc socket sod soe sog soh sop; do
            find libs/ -name "*.$s" -delete
          done

      - name: View Fedora Libs
        run: tree ./libs

      - name: Upload Libs
        uses: actions/upload-artifact@v3
        with:
          name: fedora-libs-${{ matrix.container[1] }}
          path: ./libs

  abi:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        # Artifact pairs (named) for comparison)
        artifacts: [["fedora-libs-34", "fedora-libs-35"],
                    ["fedora-libs-34", "fedora-libs-36"],
                    ["fedora-libs-34", "fedora-libs-37"],
                    ["fedora-libs-35", "fedora-libs-36"],
                    ["fedora-libs-35", "fedora-libs-37"],
                    ["fedora-libs-36", "fedora-libs-37"]]

    # Any base container will do, we already have the libs!
    container:
      image: ghcr.io/buildsi/ubuntu:ubuntu-22.04
      options: "--platform=linux/amd64"

    name: ${{ matrix.artifacts[0] }} vs ${{ matrix.artifacts[1] }}
    steps:
    - name: Make More Room
      run: |        
        rm -rf /usr/share/dotnet
        rm -rf /opt/ghc

    - name: Set inputs for start/stop indices
      env:
        start: ${{ inputs.start }}
        stop: ${{ inputs.stop }}
      run: |      
        if [ "${start}" == "" ]; then
            start=0
        fi 
        if [ "${stop}" == "" ]; then
            stop=5000
        fi 
        echo "start=${start}" >> ${GITHUB_ENV}
        echo "stop=${stop}" >> ${GITHUB_ENV}

    - name: Update container base with predictors and spliced
      uses: buildsi/smeagle-examples/actions/install@main

    - name: Checkout
      uses: actions/checkout@v3

    - name: Download First Version
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifacts[0] }}
        path: first/

    - name: Download Second Version
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifacts[1] }}
        path: second/

    - name: Reconstruct debug directories
      run: |
        cd first/usr/lib/debug
        for d in bin lib lib64 sbin; do ln -sf usr/$d $d; done
        cd -
        cd second/usr/lib/debug
        for d in bin lib lib64 sbin; do ln -sf usr/$d $d; done

    - name: View Artifacts Structure
      run: |
        ls first/
        ls second/

    - name: Compare Matching Libs        
      run: |
        # Ensure we can see Python installs
        export PATH=/opt/conda/bin:$HOME/.local/bin:$PATH
        results_dir=/tmp/results
        cache_dir=/tmp/cache
        mkdir -p ${results_dir} ${cache_dir}
        export SPLICED_SMEAGLE_CACHE_DIR=${cache_dir}
        export SPLICED_ABILAB_CACHE_DIR=${cache_dir}
        printf "Results: ${results_dir}\n"
        printf "Cache: ${cache_dir}\n"
        export PATH=/usr/local/bin:${HOME}/.local/bin:/usr/bin:$PATH
        outdir="${results_dir}/fedora"
        mkdir -p ${outdir}
        export LIBABIGAIL_DEBUGINFO_DIR1=$PWD/first/usr/lib/debug
        export LIBABIGAIL_DEBUGINFO_DIR2=$PWD/second/usr/lib/debug
        export ABILAB_DEBUGINFO_DIR1=$PWD/first/usr/lib/debug
        export ABILAB_DEBUGINFO_DIR2=$PWD/second/usr/lib/debug
        #export ABILAB_DISABLE_REPORTS=true
        printf "/opt/conda/bin/python test_libs.py ./first ./second --os_a ${{ matrix.artifacts[0] }} --os_b ${{ matrix.artifacts[1] }} --outdir ${outdir} --start ${{ env.start }} --stop ${{ env.stop }}\n"
        /opt/conda/bin/python test_libs.py ./first ./second --os_a ${{ matrix.artifacts[0] }} --os_b ${{ matrix.artifacts[1] }} --outdir ${outdir} --start ${{ env.start }} --stop ${{ env.stop }}

    - name: Save result artifact
      uses: actions/upload-artifact@v3
      with:
         name: ${{ matrix.artifacts[0] }}-vs-${{ matrix.artifacts[1] }}
         path: /tmp/results
