name: ABI Fedora Diffs
on:
  pull_request: []
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        # container, compiler inside to use, and name+version to save
        container: [['ghcr.io/buildsi/fedora:fedora-34', "34"],
                    ['ghcr.io/buildsi/fedora:fedora-35', "35"],
                    ['ghcr.io/buildsi/fedora:fedora-36', "36"],
                    ['ghcr.io/buildsi/fedora:fedora-37', "37"]]

    container:
      image: ${{ matrix.container[0] }}
      options: "--platform=linux/amd64"

    name: ${{ matrix.container[0] }} Fedora ${{ matrix.container[1] }}
    steps:
      - name: Show Job Config
        run: |
           echo ${{ matrix.container[0] }}
           echo ${{ matrix.container[1] }}

      - name: Make Space For Build
        run: |        
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Fedora Libs
        run: /bin/bash fedora_installs.sh

      - name: Move Fedora Libs
        run: |
          mkdir -p ./libs
          cp -R /lib64/* ./libs/

      - name: View Fedora Libs
        run: tree ./libs

      - name: Upload Libs
        uses: actions/upload-artifact@v3
        with:
          name: fedora-libs-${{ matrix.container[1] }}
          path: ./libs

  abi:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        lib: ["/lib64/libadwaitaqtpriv.so",
              "/lib64/libaspell.so",
              "/lib64/libboost_log.so",
              "/lib64/libclucene-core.so",
              "/lib64/libdap.so",
              "/lib64/libdcerpc-samr.so",
              "/lib64/libdjvulibre.so",
              "/lib64/dovecot/libdovecot-storage.so",
              "/lib64/libexiv2.so",
              "/lib64/libgdal.so",
              "/lib64/libgeos.so",
              "/lib64/libglibmm-2.4.so",
              "/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed/libgmpopenh264.so",
              "/lib64/libhdf5_cpp.so",
              "/lib64/libicui18n.so",
              "/lib64/libicuuc.so",
              "/lib64/dyninst/libinstructionAPI.so",
              "/lib64/libjavascriptcoregtk-4.0.so",
              "/lib64/libjxl.so",
              "/lib64/libkmldom.so",
              "/lib64/libmusicbrainz5.so",
              "/lib64/libOpenEXRUtil-3_1.so",
              "/lib64/libopenh264.so",
              "/lib64/libOSMesa.so",
              "/lib64/libproj.so",
              "/lib64/libQt5WaylandClient.so",
              "/lib64/libQt5WaylandCompositor.so",
              "/lib64/libQt5XmlPatterns.so",
              "/lib64/libSDL2_image-2.0.so",
              "/lib64/libstdc++.so",
              "/lib64/libtag.so",
              "/lib64/libreoffice/program/libuno_cppuhelpergcc3.so",
              "/lib64/libvtkRenderingCore.so",
              "/lib64/libwebrtc_audio_processing.so",
              "/lib64/libicui18n.so",
              "/lib64/libicuuc.so"]

        # Artifact pairs (named) for comparison)
        artifacts: [["fedora-libs-34", "fedora-libs-35"],
                    ["fedora-libs-34", "fedora-libs-36"],
                    ["fedora-libs-34", "fedora-libs-37"],
                    ["fedora-libs-35", "fedora-libs-36"],
                    ["fedora-libs-35", "fedora-libs-37"],
                    ["fedora-libs-36", "fedora-libs-37"]]

    name: ${{ matrix.artifacts[0] }} vs ${{ matrix.artifacts[1] }} ${{ matrix.lib }}
    steps:
    - name: Download First Version
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifacts[0] }}
        path: first/

    - name: Download Second Version
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifacts[1] }}
        path: second/

    - name: Update container base with predictors and spliced
      uses: buildsi/smeagle-examples/actions/install@main

#    - name: Run Unit Tests with Spliced
#      uses: buildsi/smeagle-examples/actions/test@main
#      with:
#        tests_dir: ${{ github.workspace }}
#        cache_dir: /tmp/cache
#        results_dir: /tmp/diff-results
#        cxx: ${{ matrix.container[1] }} 
#        compiler: ${{ matrix.container[2] }} 
#        skip_smeagle: ${{ github.event.inputs.skip_smeagle }}       

#      - name: Save result artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ matrix.container[2] }}
#          path: /tmp/diff-results

#      - name: Save Smeagle Cache
#        uses: actions/upload-artifact@v3
#        with:
#          name: cache-smeagle-${{ matrix.container[2] }}
#          path: /tmp/cache
